name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Gradle Command
      uses: eskatos/gradle-command-action@v1
      with:
        # Path to the Gradle Wrapper directory
        # wrapper-directory: # optional
        # Path to the Gradle executable
        # gradle-executable: # optional
        # Gradle version to use
        gradle-version: 4.1
        # Path to the root directory of the build
        # build-root-directory: # optional
        # Gradle command line arguments, see gradle --help
        arguments: test
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo build
        echo ...
